version: "3.7"
services:
  web:
    build: ./docker/web
    hostname: 'localhost'
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "3939:80"
  php-cli:
    build: ./docker/web
    hostname: localhost
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
